[package]
name = "verifiable-controllers"
version = "0.1.0"
edition = "2021"

[dependencies]
builtin = { path = "../verus/source/builtin" }
vstd = { path = "../verus/source/vstd" }
deps_hack = { path = "src/deps_hack" }
tungstenite = "0.20.1"
rand = "0.8"
