name: e2e Testing
run-name: e2e tests run by ${{ github.actor }}
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "doc/**"
  pull_request:
  workflow_dispatch:
jobs:
  e2e-testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.20"
      - name: Install kind
        run: go install sigs.k8s.io/kind@v0.20.0
      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
      # For rabbitmq
      - name: Build rabbitmq controller image
        run: |
          cp docker/rabbitmq-controller/Dockerfile .
          docker build -t local/rabbitmq-controller:v0.1.0 .
      - name: Create kind cluster
        run: kind create cluster --config=./e2e/deploy/kind_config.yaml
      - name: Deploy rabbitmq controller
        run: ./deploy.sh rabbitmq local
      - name: Run rabbitmq e2e tests
        run: cd e2e && cargo run -- rabbitmq
      - name: Tear down kind cluster
        run: kind delete clusters kind
      # For zookeeper
      - name: Build zookeeper controller image
        run: |
          cp docker/zookeeper-controller/Dockerfile .
          docker build -t local/zookeeper-controller:v0.1.0 .
      - name: Create kind cluster
        run: kind create cluster --config=./e2e/deploy/kind_config.yaml
      - name: Deploy zookeeper controller
        run: ./deploy.sh zookeeper local
      - name: Run zookeeper e2e tests
        run: cd e2e && cargo run -- zookeeper
      - name: Tear down kind cluster
        run: kind delete clusters kind
